# Generated by Django 2.2 on 2020-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0004_auto_20200618_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='editorial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
