# Generated by Django 2.2 on 2020-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0005_libros_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='CantCopias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='CantPags',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='Ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
