# Generated by Django 2.2 on 2020-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0006_auto_20200618_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='CantPags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
