# Generated by Django 2.2 on 2020-06-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0007_auto_20200618_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='Ubicacion',
        ),
    ]
